name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download and install Chrome
        run: |
          Invoke-WebRequest -Uri 'https://dl.google.com/chrome/install/GoogleChromeStandaloneEnterprise64.msi' -OutFile 'chrome_installer.msi' -UseBasicParsing
          Start-Process msiexec.exe -Wait -ArgumentList '/I chrome_installer.msi /quiet /qn /norestart'

      - name: Download and install ChromeDriver
        run: |
          Invoke-WebRequest -Uri 'https://chromedriver.storage.googleapis.com/124.0.6367.134/chromedriver_win32.zip' -OutFile 'chromedriver_win32.zip' -UseBasicParsing
          Expand-Archive -Path 'chromedriver_win32.zip' -DestinationPath .

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: mochawesome-report



# name: CI

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test

#       - name: Upload test results
#         uses: actions/upload-artifact@v2
#         with:
#           name: test-results
#           path: mochawesome-report